"""added profile pic

Revision ID: 06831c00cfa3
Revises: 9e0a752cac97
Create Date: 2023-09-30 00:06:47.669308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06831c00cfa3'
down_revision = '9e0a752cac97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
