"""add foreign key

Revision ID: 58b7eec0cf4d
Revises: faeb85043a6f
Create Date: 2023-09-27 20:55:17.405511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b7eec0cf4d'
down_revision = 'faeb85043a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_posts')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_posts_users', 'users', ['poster_id'], ['id'])
        batch_op.drop_column('author')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_username_constraint', ['unique_username_constraint'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('fk_posts_users', type_='foreignkey')
        batch_op.drop_column('poster_id')

    op.create_table('_alembic_tmp_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=True),
    sa.Column('poster_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], name='fk_posts_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
