"""Initital migration

Revision ID: 73567bb2c328
Revises: 
Create Date: 2023-09-17 21:17:02.711628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73567bb2c328'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hobby', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hobby')

    # ### end Alembic commands ###
